#!/usr/bin/env bash
# Configure Nginx so that its http contains a header

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo echo "Hello World!" | sudo tee "/var/www/html/index.html"
sudo sed -i '24 i \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4i permanent;' /etc/nginx/sites-enabled/default
sudo echo "Ceci n'est pas une page" | sudo tee "/var/www/html/404.html"
sudo sed -i "24 i \\\terror_page 404 /404.html;" /etc/nginx/sites-enabled/default
sudo ufw allow 'NGINX HTTP'
sudo sed -i '46 i add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart