#!/usr/bin/env bash

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo sed -i "12i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enable/default
sudo serice nginx restart
