#!/usr/bin/env bash
# Display clock
hour=0
while [ "$hour" -le 12 ]; 
do
	echo "Hour: $hour"
	while [ "$minute" -le 59 ];
	do
		echo "$minute"
		minute=$(( minute + 1))
	done
	minute=1
	hour=$(( hour + 1))
done
