#!/usr/bin/env bash
# Display clock
hour=0
while [ "$hour" -lt 13 ]; 
do
	echo "Hour: $minute"
        while [ "$minute" -lt 60 ];
         do
		    echo "$minute"
		    minute=$(( minute + 1))
        done
        minute=1
		hour=$(( hour + 1))
done
