#!/usr/bin/env bash
# Display clock
HOUR=0
while [ "$HOUR" -lt 13 ]; do
	echo "Hour: $HOUR"
	MINUTE=1
	while [ "$MINUTE" -lt 60 ]; do
		echo "$MINUTE"
		let MINUTE=MINUTE+1
		let HOUR=HOUR+1
        done
done
