#!/usr/bin/env bash
# Check if file exists, is empty and is a normal file
filename=school
if [[ -e $filename ]];
then
	echo "school file exists"
	if [[ -s $filename ]]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi

if [[ -f $filename ]];
then
	echo "school is a regular file"
fi
