#!/usr/bin/env bash
# Fixes a container such that:
# -nginx must run as nginx user
# -nginx must listen on all active IPs on port 8080

pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start